spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  error:
    include-message: always

